[patch.crates-io.rclrs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/rclrs/share/rclrs/rust"

[patch.crates-io.rosidl_runtime_rs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/rosidl_runtime_rs/share/rosidl_runtime_rs/rust"

[patch.crates-io.test_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/test_msgs/share/test_msgs/rust"

[patch.crates-io.example_interfaces]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/example_interfaces/share/example_interfaces/rust"

[patch.crates-io.action_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/action_msgs/share/action_msgs/rust"

[patch.crates-io.unique_identifier_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/unique_identifier_msgs/share/unique_identifier_msgs/rust"

[patch.crates-io.trajectory_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/trajectory_msgs/share/trajectory_msgs/rust"

[patch.crates-io.std_srvs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/std_srvs/share/std_srvs/rust"

[patch.crates-io.shape_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/shape_msgs/share/shape_msgs/rust"

[patch.crates-io.sensor_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/sensor_msgs/share/sensor_msgs/rust"

[patch.crates-io.nav_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/nav_msgs/share/nav_msgs/rust"

[patch.crates-io.diagnostic_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/diagnostic_msgs/share/diagnostic_msgs/rust"

[patch.crates-io.geometry_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/geometry_msgs/share/geometry_msgs/rust"

[patch.crates-io.actionlib_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/actionlib_msgs/share/actionlib_msgs/rust"

[patch.crates-io.std_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/std_msgs/share/std_msgs/rust"

[patch.crates-io.statistics_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/statistics_msgs/share/statistics_msgs/rust"

[patch.crates-io.rosgraph_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/rosgraph_msgs/share/rosgraph_msgs/rust"

[patch.crates-io.rclrs_example_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/rclrs_example_msgs/share/rclrs_example_msgs/rust"

[patch.crates-io.composition_interfaces]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/composition_interfaces/share/composition_interfaces/rust"

[patch.crates-io.rcl_interfaces]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/rcl_interfaces/share/rcl_interfaces/rust"

[patch.crates-io.lifecycle_msgs]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/lifecycle_msgs/share/lifecycle_msgs/rust"

[patch.crates-io.builtin_interfaces]
path = "/home/jsyun/Programming/ROS2/Rust-ROS2/rust_ros2_workshop_champ_robot/install/builtin_interfaces/share/builtin_interfaces/rust"
